# Generated by Django 5.0.2 on 2024-02-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
