# Generated by Django 5.0.2 on 2024-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_client_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(default=1981, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='sumaré', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(default='Santa Maria', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.IntegerField(default=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='street',
            field=models.CharField(default='Roberto Mange', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='uf',
            field=models.CharField(default='sp', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
