# Generated by Django 5.0.2 on 2024-03-07 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_client_address_client_cep_client_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='client',
        ),
        migrations.AddField(
            model_name='transporter',
            name='birthday',
            field=models.DateField(default='2000-01-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporter',
            name='name',
            field=models.CharField(default='Nome', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
