# Generated by Django 5.0.2 on 2024-03-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_quantity_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
