# Generated by Django 5.0.2 on 2024-04-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transporter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.transporter'),
        ),
    ]
