# Generated by Django 5.0.2 on 2024-04-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
    ]
